// config.js
require("dotenv").config();

module.exports = {
  token: process.env.TOKEN,
  clientId: process.env.CLIENT_ID,
  guildId: process.env.GUILD_ID,
  voiceChannelId: process.env.VOICE_CHANNEL_ID,
  logChannelId: process.env.LOG_CHANNEL_ID,
  autoChatChannelId: process.env.AUTO_CHAT_CHANNEL_ID,
  vcId: process.env.VC_ID,
  greetingChannelId: process.env.GREETING_CHANNEL,
  channelId: process.env.CHANNEL_ID,
  welcomeChannelId: process.env.WELCOME_CHANNEL_ID,
  goodbyeChannelId: process.env.GOODBYE_CHANNEL_ID,
  rainbowRoleIds: process.env.RAINBOW_ROLE_IDS,
  memberId: process.env.MEMBER_ID,
  adminRoleId: process.env.ADMIN_ROLE_ID,
  mutedRoleId: process.env.MUTED_ROLE_ID,
  selfUrl: process.env.SELF_URL,
  mcHost: process.env.MC_HOST,
  mcPort: process.env.MC_PORT,
  mcUsername: process.env.MC_USERNAME,

  ROLES: [
    { id: process.env.ROLE_1_ID, tag: "[OWNER]" },
    { id: process.env.ROLE_2_ID, tag: "[ADMIN]" },
    { id: process.env.ROLE_3_ID, tag: "[MOD]" },
    { id: process.env.ROLE_4_ID, tag: "[BOOST]" },
    { id: process.env.ROLE_5_ID, tag: "[CREATOR]" },
    { id: process.env.ROLE_6_ID, tag: "[ALUMNI]" },
    { id: process.env.ROLE_7_ID, tag: "[100]" },
    { id: process.env.ROLE_8_ID, tag: "[80]" },
    { id: process.env.ROLE_9_ID, tag: "[70]" },
    { id: process.env.ROLE_10_ID, tag: "[60]" },
    { id: process.env.ROLE_11_ID, tag: "[55]" },
    { id: process.env.ROLE_12_ID, tag: "[VIP]" },
    { id: process.env.ROLE_13_ID, tag: "[FRIEND]" },
    { id: process.env.ROLE_14_ID, tag: "[PARTNER]" },
    { id: process.env.ROLE_15_ID, tag: "[MEM]" },
  ],

  ROLE_DISPLAY_MAP: {
    [process.env.ROLE_1_ID]: "「 👑 」sᴇʀᴠᴇʀ ᴏᴡɴᴇʀ",
    [process.env.ROLE_2_ID]: "「 ❗ 」ᴀᴅᴍɪɴɪsᴛʀᴀᴛᴏʀ",
    [process.env.ROLE_3_ID]: "「 ❓ 」ᴍᴏᴅᴇʀᴀᴛᴏʀ",
    [process.env.ROLE_4_ID]: "「🚀」ʙᴏᴏsᴛ",
    [process.env.ROLE_5_ID]: "「📸」ᴄᴏɴᴛᴇɴᴛ ᴄʀᴇᴀᴛᴏʀ",
    [process.env.ROLE_6_ID]: "『 👨‍🎓』ᴀʟᴜᴍɴɪ",
    [process.env.ROLE_7_ID]: "「100」ᴘᴇᴇʀʟᴇꜱꜱ",
    [process.env.ROLE_8_ID]: "「80」ᴛʀᴀɴꜱᴄᴇɴᴅᴇɴᴛ",
    [process.env.ROLE_9_ID]: "「70」ꜱᴜᴘʀᴇᴍᴇ",
    [process.env.ROLE_10_ID]: "「60」ʟᴏʀᴅ",
    [process.env.ROLE_11_ID]: "「55」ᴇᴍᴘᴇʀᴏʀ",
    [process.env.ROLE_12_ID]: "『💜』Sᴘᴇsɪᴀʟ",
    [process.env.ROLE_13_ID]: "『💙』ғʀᴇɪɴᴅs",
    [process.env.ROLE_14_ID]: "「🤝」ᴘᴀʀᴛɴᴇʀsʜɪᴘ",
    [process.env.ROLE_15_ID]: "『〽️』ᴍᴇᴍʙᴇʀ",
  },
};
