name: Generate package-lock.json

on:
  workflow_dispatch:

permissions:
  contents: write   # 🔑 kasih izin push ke repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install

      - run: git config user.name "github-actions[bot]"
      - run: git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: git add package-lock.json
      - run: git commit -m "Auto-generate lockfile" || echo "No changes"

      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
